// Auto-generated by STX - do not edit
declare module 'stx/routes' {
  interface RouteMap {
    '/components/job-table': {  }
    '/components/queue-status': {  }
    '/components/stat-card': {  }
    '/layouts/app': {  }
    '/partials/sidebar': {  }
    '/': {  }
    '/batch-details': {  }
    '/batches': {  }
    '/dependencies': {  }
    '/group-details': {  }
    '/groups': {  }
    '/job-details': {  }
    '/jobs': {  }
    '/metrics': {  }
    '/monitoring': {  }
    '/queue-details': {  }
    '/queues': {  }
  }
}
