// Auto-generated by STX - do not edit
declare module "stx/routes" {
  interface RouteMap {
    '/': {  }
    '/batch-details': {  }
    '/batches': {  }
    '/dependencies': {  }
    '/group-details': {  }
    '/groups': {  }
    '/job-details': {  }
    '/jobs': {  }
    '/metrics': {  }
    '/monitoring': {  }
    '/queue-details': {  }
    '/queues': {  }
  }
}
